<?php

namespace Costo\OfertaBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * OfertaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OfertaRepository extends EntityRepository {
    /*
     * 
     */

    public function findLastNumOfertaDelProc($numero) {
        $query = $this->getEntityManager()
                ->createQuery("SELECT o.numero
                                     FROM CostoOfertaBundle:Oferta o
                                    WHERE o.numero LIKE :numero
                                    ORDER BY o.numero DESC")
                ->setParameter("numero", "CUB-OF-" . $numero . "-" . date("Y") . "-%");

        return $query->setMaxResults(1)->getResult();
    }

    public function findCategMat($id) {
        /*$q = $this->createQueryBuilder('o,c')
                ->join('o.categorias', 'c')
                ->join('c.materiales', 'm')
                ->where('o.id = :id')
                ->setParameter('id', $id)
                ->getQuery();

        return $q->getResult();*/

        $query = $this->getEntityManager()
                ->createQuery("SELECT c
                                 FROM CostoOfertaBundle:Oferta o
                                 JOIN o.categorias c
                                 JOIN c.materiales m
                                WHERE o.id = :id")
                ->setParameter('id', $id);

        return $query->getResult();
    }

}
