<?php

namespace Costo\OfertaBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * OfertaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OfertaProcesoRepository extends EntityRepository {
    
    public function findOpDeOferta($ofertaId) {
        $query = $this->getEntityManager()
                ->createQuery("SELECT o
                                 FROM CostoOfertaBundle:OfertaProceso o
                                WHERE o.oferta = :id")
                ->setParameter("id", $ofertaId);

        return $query->getResult();
    }
    
    
   //posiblemente obsoleto 
    public function existsOp($ofertaId, $procesoId) {
        $query = $this->getEntityManager()
                ->createQuery("SELECT o.id
                                 FROM CostoOfertaBundle:OfertaProceso o
                                WHERE o.oferta = :oferta
                                  AND o.proceso = :proceso")
                ->setParameter("oferta", $ofertaId)
                ->setParameter('proceso', $procesoId);

        return $query->getOneOrNullResult();
    }
    
    
    public function findOp($ofertaId, $procesoId) {
        $query = $this->getEntityManager()
                ->createQuery("SELECT o
                                 FROM CostoOfertaBundle:OfertaProceso o
                                WHERE o.oferta = :oferta
                                  AND o.proceso = :proceso")
                ->setParameter("oferta", $ofertaId)
                ->setParameter('proceso', $procesoId);

        return $query->getOneOrNullResult();
    }
    
    
    public function findOpPrincipal($ofertaId) {
        $query = $this->getEntityManager()
                ->createQuery("SELECT o
                                 FROM CostoOfertaBundle:OfertaProceso o
                                WHERE o.oferta = :oferta
                                  AND o.principal = 1")
                ->setParameter("oferta", $ofertaId);

        return $query->getOneOrNullResult();
    }
}
