<?php

namespace Costo\OfertaBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * OfertaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SitioRepository extends EntityRepository {
    
    public function findSitiosDeOferta($ofertaId) {
        $query = $this->getEntityManager()
                ->createQuery("SELECT s
                                 FROM CostoOfertaBundle:Sitio s
                                WHERE s.oferta = :id")
                ->setParameter("id", $ofertaId);

        return $query->getResult();
    }
}
