<?php

namespace Costo\ClienteBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * FichaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DirectivoRepository extends EntityRepository
{
    public function findDirectivoDeFicha($fichaId) {
        $query = $this->getEntityManager()
                ->createQuery("SELECT d
                                 FROM ClienteBundle:Directivo d
                                WHERE d.ficha = :id")
                ->setParameter('id', $fichaId);

        return $query->getResult();
    }
}
