language: php

php:
  - 5.4

before_script: composer install -n

script: phpunit -c app

pre_composer_script: |
    #!/bin/bash

    cp app/config/parameters.yml.dist app/config/parameters.yml
    sed -i -e "s/database_user:.*/database_user: root/" app/config/parameters.yml
    sed -i -e "s/database_password:.*/database_password: Secr3t/" app/config/parameters.yml

post_composer_script: |
    #!/bin/bash

    ./app/console doctrine:database:create --no-interaction
    ./app/console doctrine:schema:create --no-interaction
    ./app/console doctrine:fixtures:load --no-interaction

php_ini: |
    extension=ldap.so