security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        Costo\UsersBundle\Entity\User: sha512
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        chain_provider:
            chain:
                providers: [ldap,fos_userbundle]
        in_memory:
            memory:
                users:
                    user:  { password: userpass, roles: [ 'ROLE_USER' ] }
                    admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }
        ldap:
            id: ldap_user_provider
        fos_userbundle:
            id: fos_user.user_provider.username
        main:
            entity: { class: CostoUsersBundle:User, property: username }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main_firewall:
            pattern: ^/
            anonymous: ~
            simple_form:
            #form_login:  
                authenticator: ldap_authenticator
                provider: chain_provider
                login_path: login
                check_path: login_check
                #failure_path: reporte_custom_default_index
                #csrf_provider: form.csrf_provider
            logout: 
                path: /logout
                target: /
                invalidate_session: false


    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, roles: ROLE_ADMIN }