cuenta:
    pattern:  /
    defaults: { _controller: "ClienteBundle:Cuenta:index" }

cuenta_show:
    pattern:  /{id}/show
    defaults: { _controller: "ClienteBundle:Cuenta:show" }

cuenta_new:
    pattern:  /new
    defaults: { _controller: "ClienteBundle:Cuenta:new" }

cuenta_create:
    pattern:  /create
    defaults: { _controller: "ClienteBundle:Cuenta:create" }
    requirements: { _method: post }

cuenta_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "ClienteBundle:Cuenta:edit" }

cuenta_update:
    pattern:  /{id}/update
    defaults: { _controller: "ClienteBundle:Cuenta:update" }
    requirements: { _method: post|put }

cuenta_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "ClienteBundle:Cuenta:delete" }
    requirements: { _method: post|delete }
