<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DietasRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DietaRepository extends EntityRepository {

    public function findBySearch($data) {
        $query = $this->createQueryBuilder('d');

        if (isset($data['numero'])) {
            $query->andWhere('d.numero LIKE :numero')
                    ->setParameter('numero', '%' . $data['numero'] . '%');
        }
        if (isset($data['numeroReembolso'])) {
            $query->andWhere('d.numeroReembolso LIKE :nr')
                    ->setParameter('nr', '%' . $data['numeroReembolso'] . '%');
        }
        if (isset($data['fechaPago'])) {
            $query->andWhere('d.fechaPago = :fecha')
                    ->setParameter('fecha', $data['fechaPago']);
        }
        if (isset($data['fechaSalida'])) {
            $query->andWhere('d.fechaSalida = :fecha')
                    ->setParameter('fecha', $data['fechaSalida']);
        }
        if (isset($data['fechaRegresoReal'])) {
            $query->andWhere('d.fechaRegresoReal = :fecha')
                    ->setParameter('fecha', $data['fechaRegresoReal']);
        }
        if (isset($data['fechaLiquidado'])) {
            $query->andWhere('d.fechaLiquidado = :fecha')
                    ->setParameter('fecha', $data['fechaLiquidado']);
        }
        if (isset($data['areaBeneficiario'])) {
            $query->andWhere('d.areaBeneficiario = :area')
                    ->setParameter('area', $data['areaBeneficiario']);
        }
        if (isset($data['nombreBeneficiario'])) {
            $query->andWhere('d.nombreBeneficiario = :nombre')
                    ->setParameter('nombre', $data['nombreBeneficiario']);
        }

        return $query->getQuery()->getResult();
    }

    public function isBeneficiarioPendiente($beneficiario) {
        $query = $this->createQueryBuilder('d')
                ->andWhere('d.nombreBeneficiario = :beneficiario')
                ->andWhere('d.estado = :aprobacion OR d.estado = :liquidacion')
                ->setParameter('beneficiario', $beneficiario)
                ->setParameter('aprobacion',  'Pendiente Aprobacion')
                ->setParameter('liquidacion', 'Pendiente Liquidacion')
                ->getQuery();

        return $query->getResult();
    }

}
