<?php

namespace Costo\MaterialesBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * costoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class costoRepository extends EntityRepository
{
}
