<?php

namespace Costo\MaterialesBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * precioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class precioRepository extends EntityRepository
{
}
