<?php

namespace Costo\MaterialesBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SubcategoriaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class subcategoriaRepository extends EntityRepository {

    public function findCategDeOferta($ofertaId) {
        $q = $this->createQueryBuilder('c')
                ->join('c.ofertas', 'o')
                ->where('o.id = :id')
                ->setParameter('id', $ofertaId)
                ->getQuery();

        return $q->getResult();
    }

    public function findCategServ() {
        $q = $this->createQueryBuilder('c')
                ->join('c.servicios', 's')
                ->getQuery();

        return $q->getResult();
    }

    public function findCategMat() {
        $q = $this->createQueryBuilder('c')
                ->join('c.materiales', 'm')
                ->getQuery();

        return $q->getResult();
    }

    public function findCategMatOferta($id) {
        $q = $this->createQueryBuilder('c')
                ->join('c.materiales', 'm')
                ->join('c.ofertas', 'o')
                ->where('o.id = :id')
                ->setParameter('id', $id)
                ->getQuery();

        return $q->getResult();
    }

    public function findCategServOferta($id) {
        $q = $this->createQueryBuilder('c')
                ->join('c.servicios', 'm')
                ->join('c.ofertas', 'o')
                ->where('o.id = :id')
                ->setParameter('id', $id)
                ->getQuery();

        return $q->getResult();
    }

}
