<?php

namespace Costo\ServicioBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query;

/**
 * ServicioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProcesoRepository extends EntityRepository {

    /**
     * Find all procesos related to an oferta
     * 
     * @param int $oferta_id  The Oferta id
     * @return type
     */
    public function findProcesosRelacionadosOferta($oferta_id) {
        $query = $this->getEntityManager()
                ->createQuery("SELECT p 
                                 FROM CostoServicioBundle:Proceso p
                                 JOIN p.oferta_proceso o
                                WHERE o.oferta = :id")
                ->setParameter("id", $oferta_id);

        return $query->getResult();
    }
    

    public function findProcesoPrincipalOferta($ofertaId) {
        $query = $this->getEntityManager()
                ->createQuery("SELECT p
                                 FROM CostoServicioBundle:Proceso p
                                 JOIN p.oferta_proceso o
                                WHERE o.oferta = :id AND o.principal = 1")
                ->setParameter("id", $ofertaId);

        return $query->setMaxResults(1)->getResult();
    }
    
    public function findProcesoNum($id) {
        $query = $this->getEntityManager()
                ->createQuery("SELECT p.numero
                                 FROM CostoServicioBundle:Proceso p
                                WHERE p.id = :id")
                ->setParameter("id", $id);

        return $query->getOneOrNullResult(Query::HYDRATE_SINGLE_SCALAR);
    }
}
